export const BRAND_COLORS = [
  { label: 'navy', value: '#0b2a35' },
  { label: 'offWhite', value: '#f7f3ed' },
  { label: 'tan', value: '#ccb6a6' },
  { label: 'blue', value: '#a9c1c9' },
  { label: 'brown', value: '#7f6c60' },
  { label: 'green', value: '#878e61' },
  { label: 'gray-00', value: '#f4f4f5' },
  { label: 'gray-01', value: '#dedede' },
  { label: 'gray-02', value: '#757575' },
  { label: 'gray-03', value: '#949494' },
  { label: 'gray-04', value: '#757575' },
  // { label: 'gray-05', value: '#757575' },
  { label: 'gray-06', value: '#292929' },
  { label: 'transparent', value: 'transparent' },
  { label: 'white', value: '#FFFFFF' },
  { label: 'black', value: '#000000' },
]

export const BRAND_TEXT_COLOR_CLASSES = {
  navy: 'text-brand-navy',
  offWhite: 'text-brand-offWhite',
  tan: 'text-brand-tan',
  blue: 'text-brand-blue',
  brown: 'text-brand-brown',
  green: 'text-brand-green',
  'gray-00': 'text-brand-gray-00',
  'gray-01': 'text-brand-gray-01',
  'gray-02': 'text-brand-gray-02',
  'gray-03': 'text-brand-gray-03',
  'gray-04': 'text-brand-gray-04',
  // 'gray-05': 'text-brand-gray-05',
  'gray-06': 'text-brand-gray-06',
  transparent: 'text-transparent',
  white: 'text-white',
  black: 'text-black',
}
export const BRAND_TEXT_COLOR_HOVER_CLASSES = {
  navy: 'hover:text-brand-navy',
  offWhite: 'hover:text-brand-offWhite',
  tan: 'hover:text-brand-tan',
  blue: 'hover:text-brand-blue',
  brown: 'hover:text-brand-brown',
  green: 'hover:text-brand-green',
  'gray-00': 'hover:text-brand-gray-00',
  'gray-01': 'hover:text-brand-gray-01',
  'gray-02': 'hover:text-brand-gray-02',
  'gray-03': 'hover:text-brand-gray-03',
  'gray-04': 'hover:text-brand-gray-04',
  // 'gray-05': 'hover:text-brand-gray-05',
  'gray-06': 'hover:text-brand-gray-06',
  transparent: 'hover:text-transparent',
  white: 'hover:text-white',
  black: 'hover:text-black',
}
export const BRAND_TEXT_COLOR_FOCUS_VISIBLE_CLASSES = {
  navy: 'focus-visible:text-brand-navy',
  offWhite: 'focus-visible:text-brand-offWhite',
  tan: 'focus-visible:text-brand-tan',
  blue: 'focus-visible:text-brand-blue',
  brown: 'focus-visible:text-brand-brown',
  green: 'focus-visible:text-brand-green',
  'gray-00': 'focus-visible:text-brand-gray-00',
  'gray-01': 'focus-visible:text-brand-gray-01',
  'gray-02': 'focus-visible:text-brand-gray-02',
  'gray-03': 'focus-visible:text-brand-gray-03',
  'gray-04': 'focus-visible:text-brand-gray-04',
  // 'gray-05': 'focus-visible:text-brand-gray-05',
  'gray-06': 'focus-visible:text-brand-gray-06',
  transparent: 'focus-visible:text-transparent',
  white: 'focus-visible:text-white',
  black: 'focus-visible:text-black',
}

export const BRAND_BACKGROUND_COLOR_CLASSES = {
  navy: 'bg-brand-navy',
  offWhite: 'bg-brand-offWhite',
  tan: 'bg-brand-tan',
  blue: 'bg-brand-blue',
  brown: 'bg-brand-brown',
  green: 'bg-brand-green',
  'gray-00': 'bg-brand-gray-00',
  'gray-01': 'bg-brand-gray-01',
  'gray-02': 'bg-brand-gray-02',
  'gray-03': 'bg-brand-gray-03',
  'gray-04': 'bg-brand-gray-04',
  // 'gray-05': 'bg-brand-gray-05',
  'gray-06': 'bg-brand-gray-06',
  transparent: 'bg-transparent',
  white: 'bg-white',
  black: 'bg-black',
}

export const BRAND_BACKGROUND_COLOR_HOVER_CLASSES = {
  navy: 'hover:bg-brand-navy',
  offWhite: 'hover:bg-brand-offWhite',
  tan: 'hover:bg-brand-tan',
  blue: 'hover:bg-brand-blue',
  brown: 'hover:bg-brand-brown',
  green: 'hover:bg-brand-green',
  'gray-00': 'hover:bg-brand-gray-00',
  'gray-01': 'hover:bg-brand-gray-01',
  'gray-02': 'hover:bg-brand-gray-02',
  'gray-03': 'hover:bg-brand-gray-03',
  'gray-04': 'hover:bg-brand-gray-04',
  // 'gray-05': 'hover:bg-brand-gray-05',
  'gray-06': 'hover:bg-brand-gray-06',
  transparent: 'hover:bg-transparent',
  white: 'hover:bg-white',
  black: 'hover:bg-black',
}
export const BRAND_BACKGROUND_COLOR_FOCUS_VISIBLE_CLASSES = {
  navy: 'focus-visible:bg-brand-navy',
  offWhite: 'focus-visible:bg-brand-offWhite',
  tan: 'focus-visible:bg-brand-tan',
  blue: 'focus-visible:bg-brand-blue',
  brown: 'focus-visible:bg-brand-brown',
  green: 'focus-visible:bg-brand-green',
  'gray-00': 'focus-visible:bg-brand-gray-00',
  'gray-01': 'focus-visible:bg-brand-gray-01',
  'gray-02': 'focus-visible:bg-brand-gray-02',
  'gray-03': 'focus-visible:bg-brand-gray-03',
  'gray-04': 'focus-visible:bg-brand-gray-04',
  // 'gray-05': 'focus-visible:bg-brand-gray-05',
  'gray-06': 'focus-visible:bg-brand-gray-06',
  transparent: 'focus-visible:bg-transparent',
  white: 'focus-visible:bg-white',
  black: 'focus-visible:bg-black',
}

export const BRAND_BEFORE_BACKGROUND_COLOR_CLASSES = {
  navy: 'before:bg-brand-navy',
  offWhite: 'before:bg-brand-offWhite',
  tan: 'before:bg-brand-tan',
  blue: 'before:bg-brand-blue',
  brown: 'before:bg-brand-brown',
  green: 'before:bg-brand-green',
  'gray-00': 'before:bg-brand-gray-00',
  'gray-01': 'before:bg-brand-gray-01',
  'gray-02': 'before:bg-brand-gray-02',
  'gray-03': 'before:bg-brand-gray-03',
  'gray-04': 'before:bg-brand-gray-04',
  // 'gray-05': 'bg-brand-gray-05',
  'gray-06': 'before:bg-brand-gray-06',
  transparent: 'before:bg-transparent',
  white: 'before:bg-white',
  black: 'before:bg-black',
}
export const BRAND_BORDER_COLOR_CLASSES = {
  navy: 'border-brand-navy',
  offWhite: 'border-brand-offWhite',
  tan: 'border-brand-tan',
  blue: 'border-brand-blue',
  brown: 'border-brand-brown',
  green: 'border-brand-green',
  'gray-00': 'border-brand-gray-00',
  'gray-01': 'border-brand-gray-01',
  'gray-02': 'border-brand-gray-02',
  'gray-03': 'border-brand-gray-03',
  'gray-04': 'border-brand-gray-04',
  // 'gray-05': 'border-brand-gray-05',
  'gray-06': 'border-brand-gray-06',
  transparent: 'border-transparent',
  white: 'border-white',
  black: 'border-black',
}

export const SHOULD_USE_DARK_TEXT_BACKGROUND_COLORS = ['white', 'offWhite', 'gray-00', 'gray-01']
